In [31]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
df=pd.read_csv('SMSSpamCollection',sep='\t',names=['status','Message'])

In [6]:
df.head()

status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
len(df)

5572

In [8]:
len(df[df.status=='spam'])

747

In [9]:
df.loc[df['status']=='ham','status']=1
df.loc[df['status']=='spam','status']=0

In [10]:
df.head()

status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [11]:
X=df['Message']
Y=df['status']

In [12]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watching here:)
17      Eh u r

In [14]:
cv=CountVectorizer()

In [15]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [16]:
x_traincv=cv.fit_transform(['hi how are you,how  are you doing?',"hey what's up",'Make some Noise'])

In [17]:
x_traincv.toarray()

array([[2, 1, 0, 1, 2, 0, 0, 0, 0, 0, 2],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0]], dtype=int64)

In [18]:
cv.get_feature_names()

['are',
 'doing',
 'hey',
 'hi',
 'how',
 'make',
 'noise',
 'some',
 'up',
 'what',
 'you']

In [19]:
cv1=CountVectorizer()

In [20]:
X_traincv=cv1.fit_transform(X_train)

In [21]:
a=X_traincv.toarray()

In [22]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
cv1.inverse_transform(a[0])

[array(['an', 'for', 'good', 'hourish', 'if', 'in', 'is', 'it', 'leave',
        'movie', 'no', 'ok', 'the'], dtype='<U34')]

In [29]:
len(a[0])

7793

In [34]:
cv2=TfidfVectorizer(min_df=1,stop_words='english')

In [38]:
x_traincv2=cv2.fit_transform(['hi how are you,how  are you doing?',"hey what's up",'Make some Noise'])

In [41]:
x_traincv2.toarray()

array([[0.70710678, 0.        , 0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.70710678, 0.70710678]])

In [42]:
cv2.get_feature_names()

['doing', 'hey', 'hi', 'make', 'noise']

In [53]:
cv3=TfidfVectorizer(min_df=1,stop_words='english')

In [54]:
X_traincv=cv3.fit_transform(X_train)

In [55]:
b=X_traincv.toarray()

In [56]:
b[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [57]:
len(b[0])

7531

In [60]:
cv3.inverse_transform(b[0])

[array(['good', 'hourish', 'leave', 'movie', 'ok'], dtype='<U34')]

In [61]:
X_train.iloc[0]

"No I'm good for the movie, is it ok if I leave in an hourish?"

In [62]:
model=MultinomialNB()

In [63]:
Y_train=Y_train.astype('int')

In [64]:
model.fit(X_traincv,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [65]:
X_testcv=cv3.transform(X_test)

In [66]:
pred=model.predict(X_testcv)

In [67]:
pred

array([1, 1, 1, ..., 1, 0, 1])

In [68]:
actual=np.array(Y_test)

In [69]:
actual

array([1, 0, 1, ..., 1, 0, 1], dtype=object)

In [72]:
count=0
for i in range (len(pred)):
    if pred[i]==actual[i]:
        count=count+1

In [73]:
count

1089

In [74]:
len(pred)

1115

In [75]:
1089/1115.0

0.9766816143497757

In [76]:
pred=model.predict(X_testcv[0])

In [77]:
pred

array([1])

In [78]:
X_test.iloc[0]

'Storming msg: Wen u lift d phne, u say "HELLO" Do u knw wt is d real meaning of HELLO?? . . . It\'s d name of a girl..! . . . Yes.. And u knw who is dat girl?? "Margaret Hello" She is d girlfrnd f Grahmbell who invnted telphone... . . . . Moral:One can 4get d name of a person, bt not his girlfrnd... G o o d n i g h t . . .@'